# Generated by Django 4.2 on 2026-04-01 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='bank_statements/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('statement_period_start', models.DateField(blank=True, null=True)),
                ('statement_period_end', models.DateField(blank=True, null=True)),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_deposits', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_withdrawals', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('DIRECTOR', 'Hospital Director'), ('CFO', 'Chief Financial Officer'), ('MANAGER', 'Finance Manager'), ('ANALYST', 'Financial Analyst')], max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KPIMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=255)),
                ('metric_type', models.CharField(choices=[('REVENUE', 'Revenue Metrics'), ('COST', 'Cost Management'), ('PROFITABILITY', 'Profitability'), ('CASHFLOW', 'Cash Flow'), ('EFFICIENCY', 'Efficiency'), ('FINANCIAL_HEALTH', 'Financial Health')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit', models.CharField(max_length=50)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('warning_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('critical_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='HEALTHY', max_length=20)),
                ('calculated_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_metrics', to='kpi.bankstatement')),
            ],
            options={
                'ordering': ['-calculated_date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit/Income'), ('WITHDRAWAL', 'Withdrawal/Expense'), ('TRANSFER', 'Transfer')], max_length=20)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='kpi.bankstatement')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('INSIGHT', 'General Insight'), ('ALERT', 'Alert/Warning'), ('RECOMMENDATION', 'Recommendation'), ('FORECAST', 'Forecast'), ('RESPONSE', 'Question Response')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('related_metrics', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='kpi.bankstatement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
