# Generated by Django 4.2 on 2026-04-18 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kpi', '0002_improvements'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#2C7A5C', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('UPLOAD', 'Statement Uploaded'), ('DELETE', 'Statement Deleted'), ('REPROCESS', 'Statement Reprocessed'), ('EXPORT', 'Report Exported'), ('LOGIN', 'User Login'), ('AI_QUERY', 'AI Query Made'), ('CATEGORY_EDIT', 'Category Edited'), ('BUDGET_SET', 'Budget Target Set')], max_length=20),
        ),
        migrations.CreateModel(
            name='TwoFactorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totp_secret', models.CharField(blank=True, max_length=64)),
                ('is_enabled', models.BooleanField(default=False)),
                ('backup_codes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totp_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatementTagging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggings', to='kpi.bankstatement')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggings', to='kpi.statementtag')),
            ],
            options={
                'unique_together': {('statement', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='BudgetTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('REVENUE', 'Revenue'), ('EXPENSES', 'Expenses'), ('NET_INCOME', 'Net Income'), ('PROFIT_MARGIN', 'Profit Margin %')], max_length=20)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('period_month', models.IntegerField(help_text='1–12')),
                ('period_year', models.IntegerField()),
                ('currency', models.CharField(default='KES', max_length=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('user', 'metric', 'period_month', 'period_year')},
            },
        ),
    ]
