# Generated by Django 4.2 on 2026-05-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0004_industry_subaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='transaction_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='kpimetric',
            name='calculated_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
