# Generated by Django 4.2 on 2026-09-11 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kpi.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kpi', '0005_add_db_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('RECEIPT', 'Receipt'), ('REMITTANCE', 'Remittance Advice'), ('CONTRACT', 'Contract / Agreement'), ('KYC', 'KYC / Identity'), ('STATEMENT', 'Bank Statement'), ('CORRESPONDENCE', 'Letter / Correspondence'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=30)),
                ('department', models.CharField(choices=[('CREDIT_CONTROL', 'Credit Control'), ('FINANCE', 'Finance'), ('PROCUREMENT', 'Procurement'), ('COMPLIANCE', 'Compliance'), ('OPERATIONS', 'Operations')], db_index=True, default='CREDIT_CONTROL', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('PROCESSED', 'Processed'), ('IN_REVIEW', 'In Review'), ('CLEARED', 'Cleared'), ('FAILED', 'Extraction Failed')], db_index=True, default='PENDING', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to=kpi.models._user_upload_path)),
                ('source', models.CharField(default='UPLOAD', max_length=20)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('counterparty', models.CharField(blank=True, db_index=True, max_length=200)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('doc_date', models.DateField(blank=True, db_index=True, null=True)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('processing_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('source_statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kpi.bankstatement')),
                ('sub_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kpi.subaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', 'department'], name='kpi_documen_owner_i_cea7a9_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', 'status'], name='kpi_documen_owner_i_beb374_idx'),
        ),
    ]
